namespace ShonOffice.Domain.Ports;

/// <summary>
/// Port to the PDF processing engine. The heavy implementation
/// (parsing/layout extraction) lives in Rust and is exposed as a
/// <c>cdylib</c> via FFI in <c>ShonOffice.Infra.Native</c>; the domain only
/// knows this interface, never the bindings generated by <c>csbindgen</c>.
/// </summary>
public interface IPdfEngine
{
    /// <summary>
    /// Extracts the text of a PDF, one block/paragraph per element, as a
    /// step prior to rebuilding it as a <see cref="Documents.WordDocument"/>
    /// in the application layer.
    /// </summary>
    IReadOnlyList<string> ExtractText(string pdfFilePath);
}
